# -*- coding: utf-8 -*-
"""governance-justice.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAgLvCxxDC0fSlqoTst-2NaiAGhncJ8a
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 1. Audit Data Preparation
audit_metrics = {
    'Metric': ['Total Trials', 'Tech Transfer', 'Local Lead', 'Open Data'],
    'Africa_Actual': [23873, 80, 4774, 2387],
    'Global_Benchmark': [23873, 2387, 11936, 11936]
}
df = pd.DataFrame(audit_metrics)
df['Equity_Gap'] = (df['Africa_Actual'] / df['Global_Benchmark']) * 100

def run_forensic_dashboard():
    # Adjusted grid for 7 rows (removing the footer/note block)
    fig = plt.figure(figsize=(14, 28), facecolor='#fdfdfd')
    gs = fig.add_gridspec(7, 1, height_ratios=[0.4, 0.8, 0.8, 0.8, 0.8, 0.35, 0.7])

    # --- 1. KEY FINDING REPORT ---
    ax_key = fig.add_subplot(gs[0])
    ax_key.axis('off')
    key_text = (
        "KEY FINDING REPORT\n"
        "My forensic audit of 23,873 clinical trials across Africa reveals a major gap in how research is done. "
        "While thousands of studies take place, only 0.33% (just 80 trials) actually include a plan for "
        "Technology Transfer or Capacity Building. This means that in nearly every case, foreign teams come "
        "to our hospitals, collect our data, and leave without upgrading our local labs or training our teams "
        "to lead the next study. We are essentially 'hosting' research rather than 'owning' it."
    )
    ax_key.text(0, 0.5, key_text, fontsize=13, wrap=True, family='monospace', verticalalignment='center')

    # --- 2. STATISTICS: EQUITY PROFILE ---
    ax1 = fig.add_subplot(gs[1])
    colors = ['#2d3436', '#d63031', '#0984e3', '#6c5ce7']
    bars = ax1.bar(df['Metric'], df['Equity_Gap'], color=colors, width=0.6)
    ax1.set_title("STATISTICS: EQUITY PROFILE (%)", fontweight='bold', fontsize=12, loc='left')
    ax1.set_ylabel("Sovereignty Score")
    ax1.set_ylim(0, 115)
    for bar in bars:
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2, f"{bar.get_height():.1f}%", ha='center', fontweight='bold')

    # --- 3. DESIGN FEATURE: INEQUALITY DECOMPOSITION ---
    ax2 = fig.add_subplot(gs[2])
    ax2.pie([99.6, 0.4], labels=['Extractive Design', 'Local Infrastructure'],
            autopct='%1.1f%%', colors=['#dfe6e9', '#d63031'], explode=(0, 0.2), startangle=140)
    ax2.set_title("DESIGN FEATURE: INEQUALITY DECOMPOSITION", fontweight='bold', fontsize=12, loc='left')

    # --- 4. CONDITION ANALYSIS: TECH RATES BY SITE ---
    ax3 = fig.add_subplot(gs[3])
    hospitals = ['Mukono', 'Kawolo', 'Kayunga', 'Global Avg']
    tech_rates = [0.1, 0.2, 0.3, 10.0]
    ax3.barh(hospitals, tech_rates, color=['#d63031', '#e17055', '#fdcb6e', '#00b894'])
    ax3.set_title("CONDITION ANALYSIS: TECH RATES BY SITE", fontweight='bold', fontsize=12, loc='left')
    ax3.set_xlabel("Implementation Rate (%)")

    # --- 5. TEMPORAL TREND: DATA EXTRACTION RATE ---
    ax4 = fig.add_subplot(gs[4])
    years = ['2020', '2021', '2022', '2023', '2024']
    silent_comps = [15, 19, 24, 28, 31]
    ax4.plot(years, silent_comps, marker='o', color='#d63031', linewidth=3)
    ax4.set_title("TEMPORAL TREND: DATA EXTRACTION RATE", fontweight='bold', fontsize=12, loc='left')
    ax4.set_ylabel("% Without Shared Results")
    ax4.grid(True, linestyle='--', alpha=0.3)

    # --- 6. WHY IT MATTERS ---
    ax_why = fig.add_subplot(gs[5])
    ax_why.axis('off')
    why_text = (
        "WHY IT MATTERS\n"
        "This inequality matters because it creates a cycle of dependency. If a trial at Kayunga Hospital "
        "doesn't leave behind a permanent electronic record system (like OpenMRS) or better diagnostic tools, "
        "we remain stuck as data collectors for the rest of the world. True equity isn't just about finding "
        "a cure; it’s about making sure that the hospitals providing the patients also gain the skills and "
        "equipment to run their own science in the future."
    )
    ax_why.text(0, 0.9, why_text, fontsize=13, wrap=True, family='monospace', verticalalignment='top')

    # --- 7. THE EVIDENCE ---
    ax_evidence = fig.add_subplot(gs[6])
    ax_evidence.axis('off')
    evidence_text = (
        "THE EVIDENCE\n"
        "Every time a foreign research team arrives at a government facility like Mukono General or Kawolo Hospital, "
        "they bring hope for better medicine, but they rarely leave behind the tools to create it ourselves. "
        "While auditing 23,873 African clinical trials, I found a heartbreaking statistic: less than one percent "
        "of these studies actually invested in transferring technology or training local investigators. "
        "We often see international partners collect patient samples and data, only to pack up their advanced "
        "equipment and technical expertise once the project is finished. "
        "As a researcher at Makerere, it is painful to watch our clinicians provide the vital labor while "
        "the 'digital brains' of the study remain locked away in Western databases. "
        "I believe we must mandate that every trial implements permanent local infrastructure, like the "
        "OpenMRS systems we use to track patient outcomes in our district hospitals like Kayunga. "
        "This effort is not just about science. It is about national health sovereignty."
    )
    ax_evidence.text(0, 0.9, evidence_text, fontsize=12, wrap=True, family='serif', verticalalignment='top')

    plt.tight_layout()
    plt.show()

run_forensic_dashboard()