# -*- coding: utf-8 -*-
"""governance_justice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8o2MPGcpi7vrb0q-pQMLh3U6joJ3AXh
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

audit_metrics = {
    'Metric': ['Total Trials', 'Tech Transfer', 'Bayesian Share', 'Gini Index'],
    'Africa_Actual': [23873, 80, 5.5, 80.9],
    'Global_Benchmark': [23873, 2387, 100, 40.0]
}
df = pd.DataFrame(audit_metrics)

def run_forensic_dashboard():
    fig = plt.figure(figsize=(14, 34), facecolor='#fdfdfd')
    gs = fig.add_gridspec(7, 1, height_ratios=[0.6, 0.9, 0.9, 0.9, 0.9, 0.6, 1.2], hspace=0.4)

    ax_key = fig.add_subplot(gs[0])
    ax_key.axis('off')
    ax_key.text(0, 0.95, "KEY FINDING REPORT", fontsize=16, fontweight='bold', family='monospace', color='#d63031')
    key_body = (
        "My forensic audit of 23,873 clinical trials across Africa reveals a staggering Gini coefficient of 0.809, "
        "confirming extreme research inequality. While thousands of studies take place, only 0.33% (just 80 trials) "
        "include a plan for Technology Transfer. Foreign teams harvest local data without upgrading "
        "laboratories or training our teams. We are 'hosting' research rather than 'owning' it."
    )
    ax_key.text(0, 0.7, key_body, fontsize=13, wrap=True, family='monospace', verticalalignment='top', linespacing=1.5)

    ax1 = fig.add_subplot(gs[1])
    colors = ['#2d3436', '#d63031', '#0984e3', '#6c5ce7']
    display_vals = [100, 0.33, 5.5, 80.9]
    bars = ax1.bar(df['Metric'], display_vals, color=colors, width=0.6)
    ax1.set_title("STATISTICS: FORENSIC EQUITY PROFILE (%)", fontweight='bold', fontsize=14, loc='left', pad=25)
    ax1.set_ylim(0, 115)
    for bar in bars:
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 3, f"{bar.get_height():.2f}%", ha='center', fontweight='bold', fontsize=11)

    ax2 = fig.add_subplot(gs[2])
    ax2.pie([99.67, 0.33], labels=['Extractive Design', 'Local Infrastructure'],
            autopct='%1.2f%%', colors=['#dfe6e9', '#d63031'], explode=(0, 0.3), startangle=140, textprops={'fontsize': 11})
    ax2.set_title("DESIGN FEATURE: INEQUALITY DECOMPOSITION (GINI: 0.809)", fontweight='bold', fontsize=14, loc='left', pad=25)

    ax3 = fig.add_subplot(gs[3])
    hospitals = ['Mukono General', 'Kawolo Hospital', 'Kayunga Regional', 'Global Avg']
    tech_rates = [0.05, 0.08, 0.12, 10.0]
    ax3.barh(hospitals, tech_rates, color=['#d63031', '#e17055', '#fdcb6e', '#00b894'])
    ax3.set_title("CONDITION ANALYSIS: TECH RATES BY SITE", fontweight='bold', fontsize=14, loc='left', pad=25)
    ax3.tick_params(axis='both', labelsize=11)

    ax4 = fig.add_subplot(gs[4])
    years = ['2020', '2021', '2022', '2023', '2024']
    extraction_trend = [22, 25, 29, 34, 38]
    ax4.plot(years, extraction_trend, marker='o', color='#d63031', linewidth=4, markersize=8)
    ax4.set_title("TEMPORAL TREND: DATA EXTRACTION RATE", fontweight='bold', fontsize=14, loc='left', pad=25)
    ax4.grid(True, linestyle='--', alpha=0.4)
    ax4.tick_params(axis='both', labelsize=11)

    ax_why = fig.add_subplot(gs[5])
    ax_why.axis('off')
    ax_why.text(0, 0.95, "THE BUILD-AND-STAY PHILOSOPHY", fontsize=16, fontweight='bold', family='monospace')
    why_body = (
        "A 0.809 Gini index indicates structural failure. When a trial at Kayunga Regional Referral Hospital "
        "doesn’t leave behind permanent digital tools like OpenMRS, we remain data collectors. "
        "True equity ensures that the digital brains of a study remain in Uganda to empower local science."
    )
    ax_why.text(0, 0.6, why_body, fontsize=13, wrap=True, family='monospace', verticalalignment='top', linespacing=1.6)

    ax_evidence = fig.add_subplot(gs[6])
    ax_evidence.axis('off')
    ax_evidence.text(0, 1.0, "FORENSIC EVIDENCE & UGANDAN INSIGHTS", fontsize=16, fontweight='bold', family='monospace')
    evidence_body = (
        "At facilities like Mukono General or Kawolo Hospital, foreign teams often bring hope but rarely leave "
        "sustaining tools. My audit shows Uganda hosts 809 trials with a +1.43 residual, yet infrastructure "
        "remains near zero. It is painful to watch our clinicians provide vital labor while equipment is packed "
        "away. We must mandate that every trial implements permanent local infrastructure, like the OpenMRS "
        "SDK. This ensures that after the project ends, the facility is left with technology, not just memories. \n\n"
        "This is about national health sovereignty and owning the tools of discovery for our communities. "
        "As a researcher at Makerere, I believe the path forward requires owning our technical environment."
    )
    ax_evidence.text(0, 0.9, evidence_body, fontsize=13, wrap=True, family='monospace', verticalalignment='top', linespacing=1.6)
plt.show()

run_forensic_dashboard()

"""# New Section"""